using System;
using System.Collections.Generic;
using System.Text;

namespace Business.Services.Membership {
	//These correspond to the navigation natural key properties
	public enum NavigationSections {
		_NONE_,
		home,
		unauthorized,
		error,
		settings,
		terms_and_conditions,
		branch,
		financialsMain,
		financials,
		glinquiry,
		trialbalance,
		gldetails,
		tandebybranch,
		tandebyemployee,
		opincomeanalysis,
		forecast_to_actual,
		arinfo,
		araging,
		cashreceipts,
		unapplied_cash,
		apinfo,
		apinquiry,
		openinvoices,
		ciprecap,
		ciprecap_mtd,
		ciprecap_qtd,
		ciprecap_ytd,
		ciprecap_jtd,
		ciprecap_securals,
		ciprecap_bucket_mtd,
		ciprecap_bucket_ytd,
		ciprecap_product_line,
		estimatorPM,		
		estimatorCollectionPercent,
		estimatorRevenue,
		revenueByBranch,
		laborcontrol,
		// TODO: Navigation_Roles_PermissionContext needs to be updated alongide this
		laborcontrolhourscomparison,
		laborcontrolcostcomparison,
		laboranalysisinquiry,
		laboranalysisinquiry_laboranalysis,
		laboranalysis_detail,
		safety,
		safety_osha,
		safety_totalincidentrate,
		safety_totalincidentratebyfy,
		insurance,
		insurance_claimdetails,
		insurance_openwcclaims,
		project,
		cipinfo,
		project_laboranalysis,
		project_monthlycip,
		project_costcodehistory,
		project_bucketcip,
		clear_cache,
		user_info,
		hydrate_cache
	}
}